SchoolSystemWithCore/Controllers/DisAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using SchoolSystemWithCore.Data;
using SchoolSystemWithCore.Models;
using SchoolSystemWithCore.Models.ViewModels;

namespace SchoolSystemWithCore.Controllers
{
    public class DisAccountController : Controller
    {
        private readonly string _baseUrl = "http://sclmanagement.azurewebsites.net";
        private readonly ApplicationDbContext _context;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<ApplicationUser> _userManager;

        public DisAccountController(ApplicationDbContext context,
            RoleManager<IdentityRole> roleManager,
            UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _roleManager = roleManager;
            _userManager = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> StudentRegister(string userId, string password)
        {
            ViewBag.ClassList = await GetClassesFromApi();
            
            ViewBag.UserId = userId;
            ViewBag.Password = password;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> StudentRegister(CreateCombinedStudParentViewModel model)
        {
            var user = _userManager.FindByIdAsync(model.P_Id).Result;
            var role = _roleManager.FindByNameAsync("Student").Result;
            var parentRole = _roleManager.FindByNameAsync("Parent").Result;
            
            Student Student = new Student()
            {
                AdmissionDate = model.AdmissionDate,
                AdmissionNumber = model.AdmissionNumber,
                ApplicationUserId = model.P_Id,
                ClassRoomId = model.ClassRoomId
            };

            var parentUser = new ApplicationUser()
            {
                UserName = model.ParentEmail,
                Email = model.ParentEmail,
                Name = model.ParentName
            };
            var result = await _userManager.CreateAsync(parentUser, model.Password);
            if (result.Succeeded)
            {
                await _userManager.AddToRoleAsync(parentUser, "Parent");
            }

            Parent Parent = new Parent()
            {
                ApplicationUserId = parentUser.Id,
                PhoneNumber = model.TpNumber
            };
            var localStudentSuccess = await SaveToDatabase(Student);
            var localParentSuccess = await SaveToDatabase(Parent);

            CreateStudentViewModel StudentApi = new CreateStudentViewModel()
            {
                P_Id = user.Id,
                AdmissionDate = model.AdmissionDate,
                AdmissionNumber = model.AdmissionNumber,
                ClassRoomId = model.ClassRoomId,
                Email = user.Email,
                Name = user.Name,
                Password = model.StudentPassword,
                Role_Id = role.Id
            };

            CreateParentViewModel ParentApi = new CreateParentViewModel()
            {
                Email = model.ParentEmail,
                Name = model.ParentName,
                P_Id = parentUser.Id,
                Password = model.Password,
                Role_Id = parentRole.Id,
                TpNumber = model.TpNumber,
                StudentId = model.P_Id
            };

            var studentSuccess = await PostOnApi("AddStudentDetails", StudentApi);
            var success = await PostOnApi("ParentDetails", ParentApi);

            if (success && studentSuccess && localStudentSuccess && localParentSuccess)
            {
                ViewBag.Message = "You have successfully registered a student and a parent";
            }
            
            return RedirectToAction("Register", "Account");
        }

        [HttpGet]
        public async Task<IActionResult> TeacherRegister(string userId, string password)
        {
            ViewBag.ClassList = await GetClassesFromApi();

            ViewBag.UserId = userId;
            ViewBag.Password = password;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> TeacherRegister(CreateTeacherViewModel model)
        {
            var user = _userManager.FindByIdAsync(model.P_Id).Result;
            var role = _roleManager.FindByNameAsync("Teacher").Result;

            Teacher Teacher = new Teacher()
            {
                ApplicationUserId = model.P_Id,
                Grade = model.teacherGrade,
                OwnClass = model.ClassRoomId,
                Phone = model.TpNumber
            };

            var localSuccess = await SaveToDatabase(Teacher);

            model.Email = user.Email;
            model.Name = user.Name;
            model.Role_Id = role.Id;

            var success = await PostOnApi("TeacherDetails", model);
            if (success && localSuccess)
            {
                ViewBag.Message = "You have successfully registered a teacher";
            }
            
            return RedirectToAction("Register", "Account");
        }

        [HttpGet]
        public IActionResult PrincipalRegister(string userid, string password)
        {
            ViewBag.UserId = userid;
            ViewBag.Password = password;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> PrincipalRegister(CreatePrincipalViewModel model)
        {
            var user = _userManager.FindByIdAsync(model.P_Id).Result;
            var role = _roleManager.FindByNameAsync("Principal").Result;

            Principal Principal = new Principal()
            {
                ApplicationUserId = model.P_Id,
                Grade = model.PrincipalGrade,
                Phone = model.TpNumber
            };

            var localSuccess = await SaveToDatabase(Principal);
            
            model.Email = user.Email;
            model.Name = user.Name;
            model.Role_Id = role.Id;

            var success = await PostOnApi("PrincipalDetails", model);
            if (success)
            {
                ViewBag.Message = "You have successfully registered a principal";
            }
            
            return RedirectToAction("Register", "Account");
        }

        private async Task<bool> PostOnApi(string link, object obj)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(_baseUrl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                var singleObject = JsonConvert.SerializeObject(obj);
                var content = new StringContent(singleObject.ToString(), Encoding.UTF8, "application/json");
                HttpResponseMessage Res = await client.PostAsync("api/" + link, content);

                if (Res.IsSuccessStatusCode)
                {
                    return true;
                }
            }
            return false;
        }

        private async Task<Object> GetClassesFromApi()
        {
            List<GetClassesViewModel> classList = new List<GetClassesViewModel>();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(_baseUrl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage Res = await client.GetAsync("api/ClassRoom");

                if (Res.IsSuccessStatusCode)
                {
                    var classesResponse = Res.Content.ReadAsStringAsync().Result;
                    classList = JsonConvert.DeserializeObject<List<GetClassesViewModel>>(classesResponse);
                }
            }
            var classes = classList.OrderBy(c => c.ClassRoomName).Select(x => new { Id = x.ClassRoomId, ClassName = x.ClassRoomName });
            return new SelectList(classes, "Id", "ClassName");
        }

        private async Task<bool> SaveToDatabase(Object obj)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _context.AddAsync(obj);
                    await _context.SaveChangesAsync();
                }
                return true;
            }
            catch (Exception e)
            {
                return false;
            }
        }
    }
}

SchoolSystemWithCore/Views/DisAccount/PrincipalRegister.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
@model SchoolSystemWithCore.Models.ViewModels.CreatePrincipalViewModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Register</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <!--<link rel="stylesheet" href="~/css/site.css" />-->
        <link rel="stylesheet" href="~/css/AdminLTE.css" />
        <!-- Font Awesome -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
        <!-- Ionicons -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
        <link rel="stylesheet" href="~/css/skins/skin-blue.min.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
        <link rel="stylesheet" href="~/css/iCheck/square/blue.css">
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <!--<link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />-->
        <link rel="stylesheet" href="~/css/AdminLTE.min.css" asp-append-version="true" />
        <!-- Font Awesome -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
        <!-- Ionicons -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
        <link rel="stylesheet" href="~/css/skins/skin-blue.min.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)

</head>
<body class="hold-transition register-page">
<p>@ViewBag.Teacher</p>
<div class="register-box">
    <div class="register-logo">
        <a href="#"><b>MORA</b>Scorpions</a>
    </div>

    <div class="register-box-body">
        <p class="login-box-msg">Register a new principal</p>
        <p>Your user Id : @ViewBag.UserId</p>
        <form asp-controller="DisAccount" asp-action="PrincipalRegister" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>

            <div class="form-group has-feedback">
                <input asp-for="PrincipalGrade" class="form-control" placeholder="Grade">
                <span class="glyphicon glyphicon-user form-control-feedback"></span>
                <span asp-validation-for="PrincipalGrade" class="text-danger"></span>
            </div>
                
            <div class="form-group has-feedback">
                <input asp-for="TpNumber" class="form-control" placeholder="Phone">
                <span class="glyphicon glyphicon-user form-control-feedback"></span>
                <span asp-validation-for="TpNumber" class="text-danger"></span>
            </div>

            <input type="hidden" asp-for="P_Id" value="@ViewBag.UserId" />
            <input type="hidden" asp-for="Password" value="@ViewBag.Password" />

            <div class="row">
                <div class="col-xs-4">
                    <button id="send" type="submit" class="btn btn-primary btn-block btn-flat">Register</button>
                </div>
            </div>
        </form>
    </div>
</div>

<environment names="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <!--<script src="~/js/site.js" asp-append-version="true"></script>-->
    <script src="~/js/adminlte.js" asp-append-version="true"></script>
</environment>
<environment names="Staging,Production">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
    </script>
    <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
    </script>
    <!--<script src="~/js/site.min.js" asp-append-version="true"></script>-->
    <script src="~/js/adminlte.min.js" asp-append-version="true"></script>
</environment>

<!-- iCheck -->
<script src="~/js/icheck.min.js"></script>
<script>
    $(function() {
        $('input').iCheck({
            checkboxClass: 'icheckbox_square-blue',
            radioClass: 'iradio_square-blue',
            increaseArea: '20%' // optional
        });
    });
    var dateElement = document.querySelector('input[type="date"]');
    dateElement.value = '2017-12-11';
</script>

@{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }




</body>
</html>

SchoolSystemWithCore/Views/DisAccount/StudentRegister.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
@model SchoolSystemWithCore.Models.ViewModels.CreateCombinedStudParentViewModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Register</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <!--<link rel="stylesheet" href="~/css/site.css" />-->
        <link rel="stylesheet" href="~/css/AdminLTE.css" />
        <!-- Font Awesome -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
        <!-- Ionicons -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
        <link rel="stylesheet" href="~/css/skins/skin-blue.min.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
        <link rel="stylesheet" href="~/css/iCheck/square/blue.css">
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <!--<link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />-->
        <link rel="stylesheet" href="~/css/AdminLTE.min.css" asp-append-version="true" />
        <!-- Font Awesome -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
        <!-- Ionicons -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
        <link rel="stylesheet" href="~/css/skins/skin-blue.min.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)

</head>
<body class="hold-transition register-page">

<div class="register-box">
    <div class="register-logo">
        <a href="#"><b>MORA</b>Scorpions</a>
    </div>

    <div class="register-box-body">
        <p class="login-box-msg">Register a new student</p>
        <p>Your user Id : @ViewBag.UserId</p>
        <form asp-controller="DisAccount" asp-action="StudentRegister" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>

            <div class="form-group has-feedback">
                <input asp-for="AdmissionNumber" class="form-control" placeholder="Addmission Number">
                <span class="glyphicon glyphicon-user form-control-feedback"></span>
                <span asp-validation-for="AdmissionNumber" class="text-danger"></span>
            </div>

            <div class="form-group has-feedback">
                <input type="date" asp-for="AdmissionDate" class="form-control"/>
                <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                <span asp-validation-for="AdmissionDate" class="text-danger"></span>
            </div>

            <div class="form-group">
                <select asp-for="ClassRoomId" asp-items="@ViewBag.ClassList" class="form-control select2 select2-hidden-accessible" style="width: 100%;" tabindex="-1" aria-hidden="true">
                </select>
            </div>
            
            <p>Parent Details</p>
            
            <div class="form-group has-feedback">
                <input asp-for="ParentName" class="form-control" placeholder="Parent Name">
                <span class="glyphicon glyphicon-user form-control-feedback"></span>
                <span asp-validation-for="ParentName" class="text-danger"></span>
            </div>
            
            <div class="form-group has-feedback">
                <input type="email" asp-for="ParentEmail" class="form-control" placeholder="Parent Email">
                <span class="glyphicon glyphicon-user form-control-feedback"></span>
                <span asp-validation-for="ParentEmail" class="text-danger"></span>
            </div>
            
            <div class="form-group has-feedback">
                <input asp-for="TpNumber" class="form-control" placeholder="Parent Telephone">
                <span class="glyphicon glyphicon-user form-control-feedback"></span>
                <span asp-validation-for="TpNumber" class="text-danger"></span>
            </div>
            
            <div class="form-group has-feedback">
                <input asp-for="Password" class="form-control" placeholder="Password for Parent">
                <span class="glyphicon glyphicon-user form-control-feedback"></span>
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            
            <div class="form-group has-feedback">
                <input asp-for="ConfirmPassword" class="form-control" placeholder="Confirm Password">
                <span class="glyphicon glyphicon-user form-control-feedback"></span>
                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
            </div>

            <input type="hidden" asp-for="P_Id" value="@ViewBag.UserId"/>
            <input type="hidden" asp-for="StudentPassword" value="@ViewBag.Password"/>

            <div class="row">
                <div class="col-xs-4">
                    <button id="send" type="submit" class="btn btn-primary btn-block btn-flat">Register</button>
                </div>
            </div>
        </form>
    </div>
</div>

<environment names="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <!--<script src="~/js/site.js" asp-append-version="true"></script>-->
    <script src="~/js/adminlte.js" asp-append-version="true"></script>
</environment>
<environment names="Staging,Production">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
    </script>
    <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
    </script>
    <!--<script src="~/js/site.min.js" asp-append-version="true"></script>-->
    <script src="~/js/adminlte.min.js" asp-append-version="true"></script>
</environment>

<!-- iCheck -->
<script src="~/js/icheck.min.js"></script>
<script>
    $(function() {
        $('input').iCheck({
            checkboxClass: 'icheckbox_square-blue',
            radioClass: 'iradio_square-blue',
            increaseArea: '20%' // optional
        });
    });
    var dateElement = document.querySelector('input[type="date"]');
    dateElement.value = '2017-12-11';
</script>

@{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }




</body>
</html>

SchoolSystemWithCore/Views/DisAccount/TeacherRegister.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
@model SchoolSystemWithCore.Models.ViewModels.CreateTeacherViewModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Register</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <!--<link rel="stylesheet" href="~/css/site.css" />-->
        <link rel="stylesheet" href="~/css/AdminLTE.css" />
        <!-- Font Awesome -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
        <!-- Ionicons -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
        <link rel="stylesheet" href="~/css/skins/skin-blue.min.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
        <link rel="stylesheet" href="~/css/iCheck/square/blue.css">
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <!--<link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />-->
        <link rel="stylesheet" href="~/css/AdminLTE.min.css" asp-append-version="true" />
        <!-- Font Awesome -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
        <!-- Ionicons -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
        <link rel="stylesheet" href="~/css/skins/skin-blue.min.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)

</head>
<body class="hold-transition register-page">
    <p>@ViewBag.Teacher</p>
    <div class="register-box">
        <div class="register-logo">
            <a href="#"><b>MORA</b>Scorpions</a>
        </div>

        <div class="register-box-body">
            <p class="login-box-msg">Register a new teacher</p>
            <p>Your user Id : @ViewBag.UserId</p>
            <form asp-controller="DisAccount" asp-action="TeacherRegister" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post">
                <div asp-validation-summary="All" class="text-danger"></div>

                <div class="form-group has-feedback">
                    <input asp-for="teacherGrade" class="form-control" placeholder="Grade">
                    <span class="glyphicon glyphicon-user form-control-feedback"></span>
                    <span asp-validation-for="teacherGrade" class="text-danger"></span>
                </div>
                
                <div class="form-group has-feedback">
                    <input asp-for="TpNumber" class="form-control" placeholder="Phone">
                    <span class="glyphicon glyphicon-user form-control-feedback"></span>
                    <span asp-validation-for="TpNumber" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <select asp-for="ClassRoomId" asp-items="@ViewBag.ClassList" class="form-control select2 select2-hidden-accessible" style="width: 100%;" tabindex="-1" aria-hidden="true"></select>
                </div>

                <input type="hidden" asp-for="P_Id" value="@ViewBag.UserId" />
                <input type="hidden" asp-for="Password" value="@ViewBag.Password" />

                <div class="row">
                    <div class="col-xs-4">
                        <button id="send" type="submit" class="btn btn-primary btn-block btn-flat">Register</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <!--<script src="~/js/site.js" asp-append-version="true"></script>-->
        <script src="~/js/adminlte.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <!--<script src="~/js/site.min.js" asp-append-version="true"></script>-->
        <script src="~/js/adminlte.min.js" asp-append-version="true"></script>
    </environment>

    <!-- iCheck -->
    <script src="~/js/icheck.min.js"></script>
    <script>
    $(function() {
        $('input').iCheck({
            checkboxClass: 'icheckbox_square-blue',
            radioClass: 'iradio_square-blue',
            increaseArea: '20%' // optional
        });
    });
    var dateElement = document.querySelector('input[type="date"]');
    dateElement.value = '2017-12-11';
    </script>

    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }




</body>
</html>