SchoolSystemWithCore/Models/ViewModels/AttendanceViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SchoolSystemWithCore.Models.ViewModels
{
    public class AttendanceViewModel
    {
        [Required]
        public string Date { get; set; }
        [Required]
        public string ClassName { get; set; }
    }
}

SchoolSystemWithCore/Controllers/AttendanceController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Runtime.Serialization.Json;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using SchoolSystemWithCore.Data;
using SchoolSystemWithCore.Models.ViewModels;

namespace SchoolSystemWithCore.Controllers
{
    [Authorize]
    public class AttendanceController : Controller
    {
        private readonly string _baseUrl = "http://sclmanagement.azurewebsites.net";
        private readonly ApplicationDbContext _context;
        public AttendanceController(ApplicationDbContext context)
        {
            _context = context;
        }
        
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult GetAttendance()
        {
            return View("Index");
        }

        [HttpPost]
        public async Task<IActionResult> GetAttendance([Bind("Date", "ClassName")]AttendanceViewModel model)
        {
            List<StudentAttendance> Students = new List<StudentAttendance>();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(_baseUrl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage Res = await client.GetAsync("api/AttendanceDetails/" + model.Date + "/" + model.ClassName);
                
                if (Res.IsSuccessStatusCode)
                {
                    var AttendanceResponse = Res.Content.ReadAsStringAsync().Result;
                    Students = JsonConvert.DeserializeObject<List<StudentAttendance>>(AttendanceResponse);
                }
            }
            foreach (var Stud in Students)
            {
                Stud.Date = model.Date;
            }
            ViewBag.Date = model.Date;
            return View(Students);
        }

        [HttpPost]
        public async Task<IActionResult> SendAttendance(List<StudentAttendance> objModel)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(_baseUrl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                var StudentList = JsonConvert.SerializeObject(objModel);
                var content = new StringContent(StudentList.ToString(), Encoding.UTF8, "application/json");
                HttpResponseMessage Res = await client.PostAsync("api/AttendanceDetails", content);
                if (Res.IsSuccessStatusCode)
                {
                    ViewBag.Message = "Successfully Updated attendance!";
                }
                
            }
            ViewBag.Date = objModel.FirstOrDefault().Date;
            return View("GetAttendance", objModel);
        }
    }
}

SchoolSystemWithCore/Views/Attendance/GetAttendance.cshtml
@using System.Collections.Generic
@using System.Security.Cryptography
@using Microsoft.AspNetCore.Mvc
@using Microsoft.AspNetCore.Mvc.Rendering
@model System.Collections.Generic.List<SchoolSystemWithCore.Models.ViewModels.StudentAttendance>
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<link href="~/css/iCheck/flat/green.css" rel="stylesheet" />

<h2>Mark Students Attendance for <b>@if(ViewBag.Date != null){ @ViewBag.Date }</b></h2>
<br />

@if (ViewBag.Message != null)
{
    <div class="box box-success box-solid" style="width: 50%;">
        <div class="box-header with-border">
            <h3 class="box-title">@ViewBag.Message <a style="color:darkred; font-weight: bold;" href="@Url.Action("Index", "Attendance")">Go Back</a></h3>

            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
            </div>
        </div>
    </div>
}

<form asp-controller="Attendance" asp-action="SendAttendance" method="post">
    @for(int i=0; i<Model.Count; i++)
    {
        <div class="form-group">
            <label class="">
                <div class="icheckbox_flat-green" aria-checked="false" aria-disabled="false" style="position: relative;">
                    <input asp-for="@Model[i].PresentAbsent" type="checkbox" class="flat-red" style="position: absolute; opacity: 0;">
                    <ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; background: rgb(255, 255, 255); border: 0px; opacity: 0;"></ins>
                </div>
                @Model[i].Name
            </label>
            <input type="hidden" asp-for="@Model[i].P_Id" />
            <input type="hidden" asp-for="@Model[i].Name" />
            <input type="hidden" asp-for="@Model[i].Date"/>
        </div>

    }
    <input value="Mark and Submit" type="submit" class="btn btn-primary btn-flat" />
    <a href="@Url.Action("Index", "Attendance")" class="btn btn-flat btn-danger">Cancel</a>
</form>

@section Scripts {
    <script src="~/js/icheck.js"></script>
    <script>
        $(document).ready(function(){
            $('input').iCheck({
                checkboxClass: 'icheckbox_flat-green',
                radioClass: 'iradio_flat-red'
            });
        });
        
    </script>
}

    

SchoolSystemWithCore/Views/Attendance/Index.cshtml
@model SchoolSystemWithCore.Models.ViewModels.AttendanceViewModel

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<div class="register-box-body" style="width: 50%">
    <h2 style="text-align: center">Check Attendance</h2>
    <form asp-controller="Attendance" asp-action="GetAttendance" method="post">
        <div asp-validation-summary="All" class="text-danger"></div>
        
        <div class="form-group has-feedback">
            <input id="getIn1" asp-for="Date" type="date" class="form-control" placeholder="Date" required>
            <span class="glyphicon glyphicon-calendar form-control-feedback"></span>
            <span asp-validation-for="Date" class="text-danger"></span>
        </div>

        <div class="form-group has-feedback">
            <input id="getIn2" asp-for="ClassName" class="form-control" placeholder="Class Name | ex :- 8-A" required>
            <span class="glyphicon glyphicon-home form-control-feedback"></span>
            <span asp-validation-for="ClassName" class="text-danger"></span>
        </div>
        
        <div class="row">
            <div class="col-xs-4">
                <button type="submit" class="btn btn-primary btn-block btn-flat">Get/Mark Attendance</button>
            </div>
        </div>
    </form>
</div>

@section Scripts
{
    <script>
        var dateControl = document.querySelector('input[type="date"]');
        dateControl.value = '2017-12-11';
    </script>
}